version: "3.7"
services:
  provisioning:
    build: Dockerfile.d/provisioning
    working_dir: /workspace
    volumes:
      - provisioning-tmp:/tmp/provisioning
      - provisioning-home:/home/developer # To hold ~/{.config, .docker, ...},
      - provisioning-home:/root # for macOS
      - ${HOME}/.ssh/id_rsa:/home/developer/.ssh/id_rsa:ro
      - ${HOME}/.ssh/id_rsa:/root/.ssh/id_rsa:ro # for macOS
      - .:/workspace
    environment:
      - TF_DATA_DIR=/tmp/provisioning
    command:
      - bash
      - -c
      - |
        ansible-galaxy install --role-file requirements.yml
volumes:
  provisioning-tmp:
    driver: local
  provisioning-home:
    driver: local
