---
- name: Setup my workstation
  hosts: all
  roles:
    - role: mazgi.cargo_make
      version: "2020.1.0"
      become: true
    - role: workstation-system
      become: true
    - role: workstation-personal
