- name: Place the file to add the Go path into the PATH
  template:
    src: default/etc/profile.d/go.sh.j2
    dest: /etc/profile.d/go.sh
    mode: u=rwx,g=rx,o=rx

- name: Unarchive go
  unarchive:
    src: https://dl.google.com/go/go1.13.4.linux-amd64.tar.gz
    dest: /opt
    remote_src: true

- include_tasks: gentoo.yml
  when:
    - ansible_distribution == "Gentoo"
- include_tasks: ubuntu18.yml
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_major_version == "18"
- include_tasks: debian9.yml
  when:
    - ansible_distribution == "Debian"
    - ansible_distribution_major_version == "9"
