- name: Add Docker gpg key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
- name: Install packages for development
  apt:
    pkg:
      - curl
      - git
      - build-essential
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: Install Docker Compose via GitHub
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.25.0/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
    dest: /usr/local/bin/docker-compose
    mode: u=rwx,g=rx,o=rx
- name: Append the docker group to current user groups
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: true

- name: Install utility packages
  apt:
    pkg:
      - zsh
      - tmux
