- name: Clone zinit
  git:
    repo: https://github.com/zdharma/zinit.git
    dest: "{{ ansible_user_dir }}/.zinit/bin"

- stat:
    path: "{{ ansible_user_dir }}/.zshrc"
  register: zshrc_stat
- name: Copy zshrc if not provisioned
  when: zshrc_stat.stat.islnk is defined and zshrc_stat.stat.islnk == False
  copy:
    src: .zshrc
    dest: "{{ ansible_user_dir }}/"
    mode: u=rw,g=r,o=r

- name: Set login shell
  become: true
  user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
