- name: Clone zinit
  git:
    repo: https://github.com/zdharma/zinit.git
    dest: "{{ ansible_user_dir }}/.zinit/bin"

- name: Copy zshrc
  copy:
    src: .zshrc
    dest: "{{ ansible_user_dir }}/"
    mode: u=rw,g=r,o=r

- name: Set login shell
  become: true
  user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
