- name: Add apt repository gpg keys
  apt_key:
    url: "{{ item }}"
  with_items:
    - https://download.docker.com/linux/ubuntu/gpg
    - https://apt.llvm.org/llvm-snapshot.gpg.key

- name: Add apt repositories
  apt_repository:
    repo: "{{ item }}"
  with_items:
    - "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    - "deb http://apt.llvm.org/{{ ansible_distribution_release }}/ llvm-toolchain-{{ ansible_distribution_release }} main"
    - "deb-src http://apt.llvm.org/{{ ansible_distribution_release }}/ llvm-toolchain-{{ ansible_distribution_release }} main"

- name: Install packages for development
  apt:
    pkg:
      - apt-transport-https
      - build-essential
      - ca-certificates
      - containerd.io
      - curl
      - dialog
      - docker-ce
      - docker-ce-cli
      - git
      - gnupg-agent
      - libclang-dev
      - locales
      - netcat
      - procps
      - software-properties-common
      - unzip
      - vim

- name: Install Docker Compose via GitHub
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.25.0/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
    dest: /usr/local/bin/docker-compose
    mode: u=rwx,g=rx,o=rx
- name: Append the docker group to current user groups
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: true

- name: Install utility packages
  apt:
    pkg:
      - zsh
      - tmux
