[tasks.create-dotenv-file.linux]
dependencies = [
  "prepare"
]
condition = { files_not_exist = ["${CARGO_MAKE_WORKING_DIRECTORY}/.env"] }
script_runner = "@duckscript"
script = [
'''
out = set ""

ret_uid = exec id -u
ret_gid = exec id -g
uid = set ${ret_uid.stdout}
gid = set ${ret_gid.stdout}

out = set "${out}UID=${uid}"
out = set "${out}GID=${gid}"

!include_files ./tasks/.create-dotenv-file.project-unique-id.ds
!include_files ./tasks/.create-dotenv-file.cloudsdk-core-project.ds
!include_files ./tasks/.create-dotenv-file.parent-dns-zone-name.ds
!include_files ./tasks/.create-dotenv-file.base-domain-name.ds
!include_files ./tasks/.create-dotenv-file.acceptable-source-ipaddr-list.ds

out = set "${out}PROJECT_UNIQUE_ID=${project_unique_id}\n"
out = set "${out}CLOUDSDK_CORE_PROJECT=${gcp_project_id}\n"
out = set "${out}TF_VAR_parent_dns_zone_name=${parent_dns_zone_name}\n"
out = set "${out}TF_VAR_gcp_project_id=${gcp_project_id}\n"
out = set "${out}TF_VAR_base_domain_name=${base_domain_name}\n"
out = set "${out}TF_VAR_basename=${project_unique_id}\n"
out = set "${out}TF_VAR_acceptable_source_ipaddr_list=${acceptable_source_ipaddr_list}\n"

writefile .env ${out}
'''
]

[tasks.create-dotenv-file.mac]
dependencies = [
  "prepare"
]
condition = { files_not_exist = ["${CARGO_MAKE_WORKING_DIRECTORY}/.env"] }
script_runner = "@duckscript"
script = [
'''
out = set ""

!include_files ./tasks/.create-dotenv-file.project-unique-id.ds
!include_files ./tasks/.create-dotenv-file.cloudsdk-core-project.ds
!include_files ./tasks/.create-dotenv-file.parent-dns-zone-name.ds
!include_files ./tasks/.create-dotenv-file.base-domain-name.ds
!include_files ./tasks/.create-dotenv-file.acceptable-source-ipaddr-list.ds

out = set "${out}PROJECT_UNIQUE_ID=${project_unique_id}\n"
out = set "${out}CLOUDSDK_CORE_PROJECT=${gcp_project_id}\n"
out = set "${out}TF_VAR_parent_dns_zone_name=${parent_dns_zone_name}\n"
out = set "${out}TF_VAR_gcp_project_id=${gcp_project_id}\n"
out = set "${out}TF_VAR_base_domain_name=${base_domain_name}\n"
out = set "${out}TF_VAR_basename=${project_unique_id}\n"
out = set "${out}TF_VAR_acceptable_source_ipaddr_list=${acceptable_source_ipaddr_list}\n"

writefile .env ${out}
'''
]
